#!/usr/bin/env python3
"""Validate the JSON contract consumed by the ROS2 Cartesian preview path.

No ROS graph, serial port, CAN bus, or hardware command is opened.  This is a
portable preflight for a waypoint artifact generated by
``export_taught_grasp_ros2_waypoints.py``.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import sys
from typing import Any

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _finite_vector(values: Any, size: int, label: str) -> np.ndarray:
    result = np.asarray(values, dtype=np.float64).reshape(-1)
    if result.size != size or not np.isfinite(result).all():
        raise ValueError(f"{label} must contain {size} finite values")
    return result


def validate(payload: dict[str, Any]) -> dict[str, Any]:
    if payload.get("schema") != "xiaou_ros2_moveit_waypoints_v1":
        raise ValueError("unexpected waypoint schema")
    if payload.get("execution") != "planning_preview_only":
        raise ValueError("waypoint artifact must remain planning_preview_only")
    contract = payload.get("planner_contract")
    if not isinstance(contract, dict):
        raise ValueError("planner_contract is missing")
    if contract.get("planning_group") != "arm" or contract.get("end_effector_link") != "grasp_tcp":
        raise ValueError("unexpected MoveIt group or end effector")
    if contract.get("frame_id") != "base_link":
        raise ValueError("only base_link paths are accepted")
    if contract.get("hardware_execution") is not False:
        raise ValueError("hardware execution must be false")
    eef_step = float(contract.get("moveit_cartesian_eef_step_m"))
    if not math.isfinite(eef_step) or not 0.001 <= eef_step <= 0.050:
        raise ValueError("moveit_cartesian_eef_step_m must be in [0.001, 0.050]")
    start_state = payload.get("start_state_contract")
    if not isinstance(start_state, dict):
        raise ValueError("start_state_contract is missing")
    if start_state.get("source") != "taught_ready_pose" or start_state.get("hardware_execution") is not False:
        raise ValueError("start_state_contract must remain a taught preview-only state")
    names = start_state.get("joint_names")
    if names != [f"joint_{index}" for index in range(1, 7)]:
        raise ValueError("start_state_contract joint_names must be joint_1 through joint_6")
    start_positions = _finite_vector(
        start_state.get("joint_positions_deg"), 6, "start_state_contract joint_positions_deg"
    )
    family_preview = payload.get("grasp_family_preview")
    if not isinstance(family_preview, dict):
        raise ValueError("grasp_family_preview is missing")
    if family_preview.get("status") != "preview_ready" or family_preview.get("preview_ready") is not True:
        raise ValueError("waypoint artifact must come from a preview-ready grasp family")
    if family_preview.get("hardware_motion") is not False:
        raise ValueError("grasp_family_preview must keep hardware motion false")
    waypoints = payload.get("waypoints")
    if not isinstance(waypoints, list) or len(waypoints) < 2:
        raise ValueError("at least two waypoints are required")
    phases: list[str] = []
    names: list[str] = []
    positions: list[np.ndarray] = []
    for index, waypoint in enumerate(waypoints):
        if not isinstance(waypoint, dict):
            raise ValueError(f"waypoint {index} is not an object")
        if waypoint.get("frame_id") != "base_link":
            raise ValueError(f"waypoint {index} is not in base_link")
        name = str(waypoint.get("name") or "")
        phase = str(waypoint.get("phase") or "")
        if not name or not phase:
            raise ValueError(f"waypoint {index} lacks name or phase")
        position = _finite_vector(waypoint.get("position_m"), 3, f"waypoint {index} position_m")
        rotation = np.asarray(waypoint.get("rotation_matrix"), dtype=np.float64)
        if rotation.shape != (3, 3) or not np.isfinite(rotation).all():
            raise ValueError(f"waypoint {index} rotation_matrix is invalid")
        if not np.allclose(rotation.T @ rotation, np.eye(3), atol=1e-6) or not np.isclose(np.linalg.det(rotation), 1.0, atol=1e-6):
            raise ValueError(f"waypoint {index} rotation_matrix is not a proper rotation")
        quaternion = _finite_vector(waypoint.get("orientation_xyzw"), 4, f"waypoint {index} orientation_xyzw")
        if not np.isclose(np.linalg.norm(quaternion), 1.0, atol=1e-6):
            raise ValueError(f"waypoint {index} orientation_xyzw is not unit length")
        seed = _finite_vector(waypoint.get("joint_seed_deg"), 6, f"waypoint {index} joint_seed_deg")
        del seed
        names.append(name)
        phases.append(phase)
        positions.append(position)
    if len(set(names)) != len(names):
        raise ValueError("waypoint names must be unique")
    expected_prefix = ("raise", "transfer", "transfer", "descend")
    if tuple(phases[:4]) != expected_prefix:
        raise ValueError("path must start raise -> transfer -> transfer -> descend")
    if phases[-1] != "approach_contact" or names[-1] != "taught_side_contact":
        raise ValueError("final waypoint must be taught_side_contact")
    segment_lengths = [float(np.linalg.norm(current - previous)) for previous, current in zip(positions, positions[1:])]
    return {
        "validated": True,
        "waypoint_count": len(waypoints),
        "phase_counts": {phase: phases.count(phase) for phase in sorted(set(phases))},
        "max_cartesian_segment_m": max(segment_lengths),
        "min_cartesian_segment_m": min(segment_lengths),
        "final_waypoint": names[-1],
        "start_state_max_abs_deg": float(np.max(np.abs(start_positions))),
        "grasp_family": family_preview.get("family"),
        "hardware_execution": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--waypoints",
        type=Path,
        default=PROJECT_ROOT / "runtime" / "teach_poses" / "cola_taught_grasp_ros2_waypoints.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "runtime" / "teach_poses" / "cola_taught_grasp_ros2_waypoints_validation.json",
    )
    args = parser.parse_args()
    waypoint_path = args.waypoints if args.waypoints.is_absolute() else PROJECT_ROOT / args.waypoints
    payload = json.loads(waypoint_path.read_text(encoding="utf-8"))
    report = validate(payload)
    report.update({"offline": True, "ros_graph_started": False, "source": str(waypoint_path)})
    output = args.output if args.output.is_absolute() else PROJECT_ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
